# Generated by Django 2.2.2 on 2020-04-14 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200411_1616'),
        ('contacts', '0002_auto_20200411_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='nss',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de seguro social'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de contacto'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='OurListingInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.Listing', verbose_name='Inmueble interesado')),
            ],
            options={
                'verbose_name': 'Interés en nuestros inmuebles',
                'verbose_name_plural': 'Intereses en nuestros inmuebles',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('price_from', models.IntegerField(blank=True, null=True, verbose_name='Precio desde')),
                ('price_to', models.IntegerField(blank=True, null=True, verbose_name='Precio hasta')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Recámaras')),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Baños')),
                ('garage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cochera')),
                ('is_interested', models.BooleanField(blank=True, default=True, null=True, verbose_name='¿Sigue interesado?')),
                ('sell_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.SellType', verbose_name='Tipo de venta interesado')),
            ],
            options={
                'verbose_name': 'Intereses del prospecto',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='general_interests',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Interest', verbose_name='Intereses personales'),
        ),
        migrations.AddField(
            model_name='contact',
            name='our_listing_interest',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.OurListingInterest', verbose_name='Intereses en nuestro listado'),
        ),
    ]
