# Generated by Django 2.2 on 2020-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AddField(
            model_name='realtor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
    ]
