# Generated by Django 2.2 on 2020-04-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
    ]
